### ISSUE TITLE
Units for ephemeris don't match

### ISSUE THREAD

**Issue by breuper-tud** [Fraunhofer-IIS/ogrp#3]
The OGRP schema specifies the units of some of the ephemeris parameters to semi-circles (or semi-circles per s). However, the output produced by the GOOSE SBC uses radians for at least some of these parameters (inc_0 and arg_per, I haven't checked the others). For instance I get values around 0.95 for inc_0. That translates to 171° if semi-circles were correct, but to 54.4° if the units are actually radians.

**Comment by iiskumari** [comment]
The issue was correctly recognized. The tests of ogre ephemeris output does shows radian units.
 We observe at different systems and sources, units of some of the ephemeris parameters. 

**`systems:            Units:`**
`ogre   -                radian`          
`ogrp   -                semi-circles `
`GPS_ICD -             semi-circles `
`Rinex        -           radian` 
`Spirent     -           semi-circles` 
`Groov's book -     radian `
http://gps.sref.info/course/2d3.html : example out of GPS ephemris from GPS standard receivers which uses radian. if we follow the ogrp schema as semi-circles unit, then we have to consider the similar change in rtk and in ogre. This is not that usefull and lof of effort to change the unit only to match the schema. Hence, we change the ogrp schema to radian. please confirm, if you also agree with it.

**Comment by breuper-tud** [comment]
I agree. Most (if not all) calculation are done in radians anyway, so changing the description to radians is the best solution from my point of view.

**Comment by iiskumari** [comment]
yes, that's right. Hence, I proceed with the ogrp schema change.
